home_homepage:
    path:     /
    defaults: { _controller: HomeBundle:Default:index }
    options:
        expose: true

home_mappage:
    path: /map
    defaults: { _controller: HomeBundle:Default:map }